// Code generated by entc, DO NOT EDIT.

package playlist

const (
	// Label holds the string label denoting the playlist type in the database.
	Label = "playlist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"

	// EdgePlaylistOwner holds the string denoting the playlist_owner edge name in mutations.
	EdgePlaylistOwner = "playlist_owner"

	// Table holds the table name of the playlist in the database.
	Table = "playlists"
	// PlaylistOwnerTable is the table the holds the playlist_owner relation/edge.
	PlaylistOwnerTable = "playlists"
	// PlaylistOwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PlaylistOwnerInverseTable = "users"
	// PlaylistOwnerColumn is the table column denoting the playlist_owner relation/edge.
	PlaylistOwnerColumn = "user_playlists"
)

// Columns holds all SQL columns for playlist fields.
var Columns = []string{
	FieldID,
	FieldPlaylistID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Playlist type.
var ForeignKeys = []string{
	"user_playlists",
}
