// Code generated by entc, DO NOT EDIT.

package playlist

const (
	// Label holds the string label denoting the playlist type in the database.
	Label = "playlist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"

	// EdgePlaylistVideos holds the string denoting the playlist_videos edge name in mutations.
	EdgePlaylistVideos = "playlist_videos"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the playlist in the database.
	Table = "playlists"
	// PlaylistVideosTable is the table the holds the playlist_videos relation/edge.
	PlaylistVideosTable = "playlist_videos"
	// PlaylistVideosInverseTable is the table name for the PlaylistVideo entity.
	// It exists in this package in order to avoid circular dependency with the "playlistvideo" package.
	PlaylistVideosInverseTable = "playlist_videos"
	// PlaylistVideosColumn is the table column denoting the playlist_videos relation/edge.
	PlaylistVideosColumn = "playlist_playlist_videos"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "playlists"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_playlists"
)

// Columns holds all SQL columns for playlist fields.
var Columns = []string{
	FieldID,
	FieldPlaylistID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Playlist type.
var ForeignKeys = []string{
	"user_playlists",
}
