// Code generated by entc, DO NOT EDIT.

package playlist

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/pongsakorn-maker/entgo-playground/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...int) predicate.Playlist {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Playlist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPlaylistID), v...))
	})
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...int) predicate.Playlist {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Playlist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPlaylistID), v...))
	})
}

// PlaylistIDGT applies the GT predicate on the "playlist_id" field.
func PlaylistIDGT(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDGTE applies the GTE predicate on the "playlist_id" field.
func PlaylistIDGTE(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDLT applies the LT predicate on the "playlist_id" field.
func PlaylistIDLT(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPlaylistID), v))
	})
}

// PlaylistIDLTE applies the LTE predicate on the "playlist_id" field.
func PlaylistIDLTE(v int) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPlaylistID), v))
	})
}

// HasPlaylistVideos applies the HasEdge predicate on the "playlist_videos" edge.
func HasPlaylistVideos() predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlaylistVideosTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistVideosTable, PlaylistVideosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistVideosWith applies the HasEdge predicate on the "playlist_videos" edge with a given conditions (other predicates).
func HasPlaylistVideosWith(preds ...predicate.PlaylistVideo) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlaylistVideosInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistVideosTable, PlaylistVideosColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		p(s.Not())
	})
}
