// Code generated by entc, DO NOT EDIT.

package playlistvideo

const (
	// Label holds the string label denoting the playlistvideo type in the database.
	Label = "playlist_video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistVideoID holds the string denoting the playlistvideo_id field in the database.
	FieldPlaylistVideoID = "playlist_video_id"

	// Table holds the table name of the playlistvideo in the database.
	Table = "playlist_videos"
)

// Columns holds all SQL columns for playlistvideo fields.
var Columns = []string{
	FieldID,
	FieldPlaylistVideoID,
}
