// Code generated by entc, DO NOT EDIT.

package playlistvideo

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/pongsakorn-maker/entgo-playground/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PlaylistVideoID applies equality check predicate on the "PlaylistVideo_ID" field. It's identical to PlaylistVideoIDEQ.
func PlaylistVideoID(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDEQ applies the EQ predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDEQ(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDNEQ applies the NEQ predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDNEQ(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDIn applies the In predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDIn(vs ...int) predicate.PlaylistVideo {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPlaylistVideoID), v...))
	})
}

// PlaylistVideoIDNotIn applies the NotIn predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDNotIn(vs ...int) predicate.PlaylistVideo {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPlaylistVideoID), v...))
	})
}

// PlaylistVideoIDGT applies the GT predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDGT(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDGTE applies the GTE predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDGTE(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDLT applies the LT predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDLT(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPlaylistVideoID), v))
	})
}

// PlaylistVideoIDLTE applies the LTE predicate on the "PlaylistVideo_ID" field.
func PlaylistVideoIDLTE(v int) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPlaylistVideoID), v))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.PlaylistVideo) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.PlaylistVideo) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaylistVideo) predicate.PlaylistVideo {
	return predicate.PlaylistVideo(func(s *sql.Selector) {
		p(s.Not())
	})
}
