// Code generated by entc, DO NOT EDIT.

package resolution

const (
	// Label holds the string label denoting the resolution type in the database.
	Label = "resolution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResolutionID holds the string denoting the resolution_id field in the database.
	FieldResolutionID = "resolution_id"

	// EdgePlaylistVideos holds the string denoting the playlist_videos edge name in mutations.
	EdgePlaylistVideos = "playlist_videos"

	// Table holds the table name of the resolution in the database.
	Table = "resolutions"
	// PlaylistVideosTable is the table the holds the playlist_videos relation/edge.
	PlaylistVideosTable = "playlist_videos"
	// PlaylistVideosInverseTable is the table name for the PlaylistVideo entity.
	// It exists in this package in order to avoid circular dependency with the "playlistvideo" package.
	PlaylistVideosInverseTable = "playlist_videos"
	// PlaylistVideosColumn is the table column denoting the playlist_videos relation/edge.
	PlaylistVideosColumn = "resolution_id"
)

// Columns holds all SQL columns for resolution fields.
var Columns = []string{
	FieldID,
	FieldResolutionID,
}
