// Code generated by entc, DO NOT EDIT.

package resolution

const (
	// Label holds the string label denoting the resolution type in the database.
	Label = "resolution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResolutionID holds the string denoting the resolution_id field in the database.
	FieldResolutionID = "resolution_id"

	// Table holds the table name of the resolution in the database.
	Table = "resolutions"
)

// Columns holds all SQL columns for resolution fields.
var Columns = []string{
	FieldID,
	FieldResolutionID,
}
