// Code generated by entc, DO NOT EDIT.

package resolution

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/pongsakorn-maker/entgo-playground/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldResolution), v))
	})
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldResolution), v))
	})
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldResolution), v))
	})
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.Resolution {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Resolution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldResolution), v...))
	})
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.Resolution {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Resolution(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldResolution), v...))
	})
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldResolution), v))
	})
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldResolution), v))
	})
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldResolution), v))
	})
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldResolution), v))
	})
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldResolution), v))
	})
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldResolution), v))
	})
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldResolution), v))
	})
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldResolution), v))
	})
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldResolution), v))
	})
}

// HasPlaylistVideos applies the HasEdge predicate on the "playlist_videos" edge.
func HasPlaylistVideos() predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlaylistVideosTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistVideosTable, PlaylistVideosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistVideosWith applies the HasEdge predicate on the "playlist_videos" edge with a given conditions (other predicates).
func HasPlaylistVideosWith(preds ...predicate.PlaylistVideo) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PlaylistVideosInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistVideosTable, PlaylistVideosColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Resolution) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Resolution) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Resolution) predicate.Resolution {
	return predicate.Resolution(func(s *sql.Selector) {
		p(s.Not())
	})
}
