// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"

	"github.com/pongsakorn-maker/entgo-playground/ent/playlist"
	"github.com/pongsakorn-maker/entgo-playground/ent/playlistvideo"
	"github.com/pongsakorn-maker/entgo-playground/ent/resolution"
	"github.com/pongsakorn-maker/entgo-playground/ent/user"
	"github.com/pongsakorn-maker/entgo-playground/ent/video"

	"github.com/facebook/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePlaylist      = "Playlist"
	TypePlaylistVideo = "PlaylistVideo"
	TypeResolution    = "Resolution"
	TypeUser          = "User"
	TypeVideo         = "Video"
)

// PlaylistMutation represents an operation that mutate the Playlists
// nodes in the graph.
type PlaylistMutation struct {
	config
	op                     Op
	typ                    string
	id                     *int
	clearedFields          map[string]struct{}
	playlist_videos        map[int]struct{}
	removedplaylist_videos map[int]struct{}
	owner                  *int
	clearedowner           bool
	done                   bool
	oldValue               func(context.Context) (*Playlist, error)
}

var _ ent.Mutation = (*PlaylistMutation)(nil)

// playlistOption allows to manage the mutation configuration using functional options.
type playlistOption func(*PlaylistMutation)

// newPlaylistMutation creates new mutation for $n.Name.
func newPlaylistMutation(c config, op Op, opts ...playlistOption) *PlaylistMutation {
	m := &PlaylistMutation{
		config:        c,
		op:            op,
		typ:           TypePlaylist,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPlaylistID sets the id field of the mutation.
func withPlaylistID(id int) playlistOption {
	return func(m *PlaylistMutation) {
		var (
			err   error
			once  sync.Once
			value *Playlist
		)
		m.oldValue = func(ctx context.Context) (*Playlist, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Playlist.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPlaylist sets the old Playlist of the mutation.
func withPlaylist(node *Playlist) playlistOption {
	return func(m *PlaylistMutation) {
		m.oldValue = func(context.Context) (*Playlist, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PlaylistMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PlaylistMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *PlaylistMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// AddPlaylistVideoIDs adds the playlist_videos edge to PlaylistVideo by ids.
func (m *PlaylistMutation) AddPlaylistVideoIDs(ids ...int) {
	if m.playlist_videos == nil {
		m.playlist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.playlist_videos[ids[i]] = struct{}{}
	}
}

// RemovePlaylistVideoIDs removes the playlist_videos edge to PlaylistVideo by ids.
func (m *PlaylistMutation) RemovePlaylistVideoIDs(ids ...int) {
	if m.removedplaylist_videos == nil {
		m.removedplaylist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.removedplaylist_videos[ids[i]] = struct{}{}
	}
}

// RemovedPlaylistVideos returns the removed ids of playlist_videos.
func (m *PlaylistMutation) RemovedPlaylistVideosIDs() (ids []int) {
	for id := range m.removedplaylist_videos {
		ids = append(ids, id)
	}
	return
}

// PlaylistVideosIDs returns the playlist_videos ids in the mutation.
func (m *PlaylistMutation) PlaylistVideosIDs() (ids []int) {
	for id := range m.playlist_videos {
		ids = append(ids, id)
	}
	return
}

// ResetPlaylistVideos reset all changes of the "playlist_videos" edge.
func (m *PlaylistMutation) ResetPlaylistVideos() {
	m.playlist_videos = nil
	m.removedplaylist_videos = nil
}

// SetOwnerID sets the owner edge to User by id.
func (m *PlaylistMutation) SetOwnerID(id int) {
	m.owner = &id
}

// ClearOwner clears the owner edge to User.
func (m *PlaylistMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared returns if the edge owner was cleared.
func (m *PlaylistMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the owner id in the mutation.
func (m *PlaylistMutation) OwnerID() (id int, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the owner ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *PlaylistMutation) OwnerIDs() (ids []int) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner reset all changes of the "owner" edge.
func (m *PlaylistMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// Op returns the operation name.
func (m *PlaylistMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Playlist).
func (m *PlaylistMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *PlaylistMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *PlaylistMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *PlaylistMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Playlist field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PlaylistMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Playlist field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *PlaylistMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *PlaylistMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PlaylistMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown Playlist numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *PlaylistMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *PlaylistMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *PlaylistMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Playlist nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *PlaylistMutation) ResetField(name string) error {
	return fmt.Errorf("unknown Playlist field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *PlaylistMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.playlist_videos != nil {
		edges = append(edges, playlist.EdgePlaylistVideos)
	}
	if m.owner != nil {
		edges = append(edges, playlist.EdgeOwner)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *PlaylistMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case playlist.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.playlist_videos))
		for id := range m.playlist_videos {
			ids = append(ids, id)
		}
		return ids
	case playlist.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *PlaylistMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedplaylist_videos != nil {
		edges = append(edges, playlist.EdgePlaylistVideos)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *PlaylistMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case playlist.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.removedplaylist_videos))
		for id := range m.removedplaylist_videos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *PlaylistMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, playlist.EdgeOwner)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *PlaylistMutation) EdgeCleared(name string) bool {
	switch name {
	case playlist.EdgeOwner:
		return m.clearedowner
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *PlaylistMutation) ClearEdge(name string) error {
	switch name {
	case playlist.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Playlist unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *PlaylistMutation) ResetEdge(name string) error {
	switch name {
	case playlist.EdgePlaylistVideos:
		m.ResetPlaylistVideos()
		return nil
	case playlist.EdgeOwner:
		m.ResetOwner()
		return nil
	}
	return fmt.Errorf("unknown Playlist edge %s", name)
}

// PlaylistVideoMutation represents an operation that mutate the PlaylistVideos
// nodes in the graph.
type PlaylistVideoMutation struct {
	config
	op                Op
	typ               string
	id                *int
	clearedFields     map[string]struct{}
	video             *int
	clearedvideo      bool
	playlists         *int
	clearedplaylists  bool
	resolution        *int
	clearedresolution bool
	done              bool
	oldValue          func(context.Context) (*PlaylistVideo, error)
}

var _ ent.Mutation = (*PlaylistVideoMutation)(nil)

// playlistvideoOption allows to manage the mutation configuration using functional options.
type playlistvideoOption func(*PlaylistVideoMutation)

// newPlaylistVideoMutation creates new mutation for $n.Name.
func newPlaylistVideoMutation(c config, op Op, opts ...playlistvideoOption) *PlaylistVideoMutation {
	m := &PlaylistVideoMutation{
		config:        c,
		op:            op,
		typ:           TypePlaylistVideo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPlaylistVideoID sets the id field of the mutation.
func withPlaylistVideoID(id int) playlistvideoOption {
	return func(m *PlaylistVideoMutation) {
		var (
			err   error
			once  sync.Once
			value *PlaylistVideo
		)
		m.oldValue = func(ctx context.Context) (*PlaylistVideo, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PlaylistVideo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPlaylistVideo sets the old PlaylistVideo of the mutation.
func withPlaylistVideo(node *PlaylistVideo) playlistvideoOption {
	return func(m *PlaylistVideoMutation) {
		m.oldValue = func(context.Context) (*PlaylistVideo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PlaylistVideoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PlaylistVideoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *PlaylistVideoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetVideoID sets the video edge to Video by id.
func (m *PlaylistVideoMutation) SetVideoID(id int) {
	m.video = &id
}

// ClearVideo clears the video edge to Video.
func (m *PlaylistVideoMutation) ClearVideo() {
	m.clearedvideo = true
}

// VideoCleared returns if the edge video was cleared.
func (m *PlaylistVideoMutation) VideoCleared() bool {
	return m.clearedvideo
}

// VideoID returns the video id in the mutation.
func (m *PlaylistVideoMutation) VideoID() (id int, exists bool) {
	if m.video != nil {
		return *m.video, true
	}
	return
}

// VideoIDs returns the video ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// VideoID instead. It exists only for internal usage by the builders.
func (m *PlaylistVideoMutation) VideoIDs() (ids []int) {
	if id := m.video; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetVideo reset all changes of the "video" edge.
func (m *PlaylistVideoMutation) ResetVideo() {
	m.video = nil
	m.clearedvideo = false
}

// SetPlaylistsID sets the playlists edge to Playlist by id.
func (m *PlaylistVideoMutation) SetPlaylistsID(id int) {
	m.playlists = &id
}

// ClearPlaylists clears the playlists edge to Playlist.
func (m *PlaylistVideoMutation) ClearPlaylists() {
	m.clearedplaylists = true
}

// PlaylistsCleared returns if the edge playlists was cleared.
func (m *PlaylistVideoMutation) PlaylistsCleared() bool {
	return m.clearedplaylists
}

// PlaylistsID returns the playlists id in the mutation.
func (m *PlaylistVideoMutation) PlaylistsID() (id int, exists bool) {
	if m.playlists != nil {
		return *m.playlists, true
	}
	return
}

// PlaylistsIDs returns the playlists ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// PlaylistsID instead. It exists only for internal usage by the builders.
func (m *PlaylistVideoMutation) PlaylistsIDs() (ids []int) {
	if id := m.playlists; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPlaylists reset all changes of the "playlists" edge.
func (m *PlaylistVideoMutation) ResetPlaylists() {
	m.playlists = nil
	m.clearedplaylists = false
}

// SetResolutionID sets the resolution edge to Resolution by id.
func (m *PlaylistVideoMutation) SetResolutionID(id int) {
	m.resolution = &id
}

// ClearResolution clears the resolution edge to Resolution.
func (m *PlaylistVideoMutation) ClearResolution() {
	m.clearedresolution = true
}

// ResolutionCleared returns if the edge resolution was cleared.
func (m *PlaylistVideoMutation) ResolutionCleared() bool {
	return m.clearedresolution
}

// ResolutionID returns the resolution id in the mutation.
func (m *PlaylistVideoMutation) ResolutionID() (id int, exists bool) {
	if m.resolution != nil {
		return *m.resolution, true
	}
	return
}

// ResolutionIDs returns the resolution ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// ResolutionID instead. It exists only for internal usage by the builders.
func (m *PlaylistVideoMutation) ResolutionIDs() (ids []int) {
	if id := m.resolution; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetResolution reset all changes of the "resolution" edge.
func (m *PlaylistVideoMutation) ResetResolution() {
	m.resolution = nil
	m.clearedresolution = false
}

// Op returns the operation name.
func (m *PlaylistVideoMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (PlaylistVideo).
func (m *PlaylistVideoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *PlaylistVideoMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *PlaylistVideoMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *PlaylistVideoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown PlaylistVideo field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PlaylistVideoMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PlaylistVideo field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *PlaylistVideoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *PlaylistVideoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PlaylistVideoMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown PlaylistVideo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *PlaylistVideoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *PlaylistVideoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *PlaylistVideoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PlaylistVideo nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *PlaylistVideoMutation) ResetField(name string) error {
	return fmt.Errorf("unknown PlaylistVideo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *PlaylistVideoMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.video != nil {
		edges = append(edges, playlistvideo.EdgeVideo)
	}
	if m.playlists != nil {
		edges = append(edges, playlistvideo.EdgePlaylists)
	}
	if m.resolution != nil {
		edges = append(edges, playlistvideo.EdgeResolution)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *PlaylistVideoMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case playlistvideo.EdgeVideo:
		if id := m.video; id != nil {
			return []ent.Value{*id}
		}
	case playlistvideo.EdgePlaylists:
		if id := m.playlists; id != nil {
			return []ent.Value{*id}
		}
	case playlistvideo.EdgeResolution:
		if id := m.resolution; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *PlaylistVideoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *PlaylistVideoMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *PlaylistVideoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedvideo {
		edges = append(edges, playlistvideo.EdgeVideo)
	}
	if m.clearedplaylists {
		edges = append(edges, playlistvideo.EdgePlaylists)
	}
	if m.clearedresolution {
		edges = append(edges, playlistvideo.EdgeResolution)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *PlaylistVideoMutation) EdgeCleared(name string) bool {
	switch name {
	case playlistvideo.EdgeVideo:
		return m.clearedvideo
	case playlistvideo.EdgePlaylists:
		return m.clearedplaylists
	case playlistvideo.EdgeResolution:
		return m.clearedresolution
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *PlaylistVideoMutation) ClearEdge(name string) error {
	switch name {
	case playlistvideo.EdgeVideo:
		m.ClearVideo()
		return nil
	case playlistvideo.EdgePlaylists:
		m.ClearPlaylists()
		return nil
	case playlistvideo.EdgeResolution:
		m.ClearResolution()
		return nil
	}
	return fmt.Errorf("unknown PlaylistVideo unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *PlaylistVideoMutation) ResetEdge(name string) error {
	switch name {
	case playlistvideo.EdgeVideo:
		m.ResetVideo()
		return nil
	case playlistvideo.EdgePlaylists:
		m.ResetPlaylists()
		return nil
	case playlistvideo.EdgeResolution:
		m.ResetResolution()
		return nil
	}
	return fmt.Errorf("unknown PlaylistVideo edge %s", name)
}

// ResolutionMutation represents an operation that mutate the Resolutions
// nodes in the graph.
type ResolutionMutation struct {
	config
	op                     Op
	typ                    string
	id                     *int
	resolution             *string
	clearedFields          map[string]struct{}
	playlist_videos        map[int]struct{}
	removedplaylist_videos map[int]struct{}
	done                   bool
	oldValue               func(context.Context) (*Resolution, error)
}

var _ ent.Mutation = (*ResolutionMutation)(nil)

// resolutionOption allows to manage the mutation configuration using functional options.
type resolutionOption func(*ResolutionMutation)

// newResolutionMutation creates new mutation for $n.Name.
func newResolutionMutation(c config, op Op, opts ...resolutionOption) *ResolutionMutation {
	m := &ResolutionMutation{
		config:        c,
		op:            op,
		typ:           TypeResolution,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withResolutionID sets the id field of the mutation.
func withResolutionID(id int) resolutionOption {
	return func(m *ResolutionMutation) {
		var (
			err   error
			once  sync.Once
			value *Resolution
		)
		m.oldValue = func(ctx context.Context) (*Resolution, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Resolution.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withResolution sets the old Resolution of the mutation.
func withResolution(node *Resolution) resolutionOption {
	return func(m *ResolutionMutation) {
		m.oldValue = func(context.Context) (*Resolution, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ResolutionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ResolutionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *ResolutionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetResolution sets the resolution field.
func (m *ResolutionMutation) SetResolution(s string) {
	m.resolution = &s
}

// Resolution returns the resolution value in the mutation.
func (m *ResolutionMutation) Resolution() (r string, exists bool) {
	v := m.resolution
	if v == nil {
		return
	}
	return *v, true
}

// OldResolution returns the old resolution value of the Resolution.
// If the Resolution object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *ResolutionMutation) OldResolution(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldResolution is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldResolution requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResolution: %w", err)
	}
	return oldValue.Resolution, nil
}

// ResetResolution reset all changes of the "resolution" field.
func (m *ResolutionMutation) ResetResolution() {
	m.resolution = nil
}

// AddPlaylistVideoIDs adds the playlist_videos edge to PlaylistVideo by ids.
func (m *ResolutionMutation) AddPlaylistVideoIDs(ids ...int) {
	if m.playlist_videos == nil {
		m.playlist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.playlist_videos[ids[i]] = struct{}{}
	}
}

// RemovePlaylistVideoIDs removes the playlist_videos edge to PlaylistVideo by ids.
func (m *ResolutionMutation) RemovePlaylistVideoIDs(ids ...int) {
	if m.removedplaylist_videos == nil {
		m.removedplaylist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.removedplaylist_videos[ids[i]] = struct{}{}
	}
}

// RemovedPlaylistVideos returns the removed ids of playlist_videos.
func (m *ResolutionMutation) RemovedPlaylistVideosIDs() (ids []int) {
	for id := range m.removedplaylist_videos {
		ids = append(ids, id)
	}
	return
}

// PlaylistVideosIDs returns the playlist_videos ids in the mutation.
func (m *ResolutionMutation) PlaylistVideosIDs() (ids []int) {
	for id := range m.playlist_videos {
		ids = append(ids, id)
	}
	return
}

// ResetPlaylistVideos reset all changes of the "playlist_videos" edge.
func (m *ResolutionMutation) ResetPlaylistVideos() {
	m.playlist_videos = nil
	m.removedplaylist_videos = nil
}

// Op returns the operation name.
func (m *ResolutionMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Resolution).
func (m *ResolutionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *ResolutionMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.resolution != nil {
		fields = append(fields, resolution.FieldResolution)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *ResolutionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case resolution.FieldResolution:
		return m.Resolution()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *ResolutionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case resolution.FieldResolution:
		return m.OldResolution(ctx)
	}
	return nil, fmt.Errorf("unknown Resolution field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ResolutionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case resolution.FieldResolution:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResolution(v)
		return nil
	}
	return fmt.Errorf("unknown Resolution field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *ResolutionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *ResolutionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *ResolutionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Resolution numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *ResolutionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *ResolutionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *ResolutionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Resolution nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *ResolutionMutation) ResetField(name string) error {
	switch name {
	case resolution.FieldResolution:
		m.ResetResolution()
		return nil
	}
	return fmt.Errorf("unknown Resolution field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *ResolutionMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.playlist_videos != nil {
		edges = append(edges, resolution.EdgePlaylistVideos)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *ResolutionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case resolution.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.playlist_videos))
		for id := range m.playlist_videos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *ResolutionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedplaylist_videos != nil {
		edges = append(edges, resolution.EdgePlaylistVideos)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *ResolutionMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case resolution.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.removedplaylist_videos))
		for id := range m.removedplaylist_videos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *ResolutionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *ResolutionMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *ResolutionMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Resolution unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *ResolutionMutation) ResetEdge(name string) error {
	switch name {
	case resolution.EdgePlaylistVideos:
		m.ResetPlaylistVideos()
		return nil
	}
	return fmt.Errorf("unknown Resolution edge %s", name)
}

// UserMutation represents an operation that mutate the Users
// nodes in the graph.
type UserMutation struct {
	config
	op               Op
	typ              string
	id               *int
	email            *string
	password         *string
	age              *int
	addage           *int
	name             *string
	clearedFields    map[string]struct{}
	playlists        map[int]struct{}
	removedplaylists map[int]struct{}
	videos           map[int]struct{}
	removedvideos    map[int]struct{}
	done             bool
	oldValue         func(context.Context) (*User, error)
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows to manage the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for $n.Name.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the id field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetEmail sets the email field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the email value in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old email value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldEmail is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail reset all changes of the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetPassword sets the password field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the password value in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old password value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPassword is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword reset all changes of the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetAge sets the age field.
func (m *UserMutation) SetAge(i int) {
	m.age = &i
	m.addage = nil
}

// Age returns the age value in the mutation.
func (m *UserMutation) Age() (r int, exists bool) {
	v := m.age
	if v == nil {
		return
	}
	return *v, true
}

// OldAge returns the old age value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldAge(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldAge is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldAge requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAge: %w", err)
	}
	return oldValue.Age, nil
}

// AddAge adds i to age.
func (m *UserMutation) AddAge(i int) {
	if m.addage != nil {
		*m.addage += i
	} else {
		m.addage = &i
	}
}

// AddedAge returns the value that was added to the age field in this mutation.
func (m *UserMutation) AddedAge() (r int, exists bool) {
	v := m.addage
	if v == nil {
		return
	}
	return *v, true
}

// ResetAge reset all changes of the "age" field.
func (m *UserMutation) ResetAge() {
	m.age = nil
	m.addage = nil
}

// SetName sets the name field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the name value in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old name value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName reset all changes of the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// AddPlaylistIDs adds the playlists edge to Playlist by ids.
func (m *UserMutation) AddPlaylistIDs(ids ...int) {
	if m.playlists == nil {
		m.playlists = make(map[int]struct{})
	}
	for i := range ids {
		m.playlists[ids[i]] = struct{}{}
	}
}

// RemovePlaylistIDs removes the playlists edge to Playlist by ids.
func (m *UserMutation) RemovePlaylistIDs(ids ...int) {
	if m.removedplaylists == nil {
		m.removedplaylists = make(map[int]struct{})
	}
	for i := range ids {
		m.removedplaylists[ids[i]] = struct{}{}
	}
}

// RemovedPlaylists returns the removed ids of playlists.
func (m *UserMutation) RemovedPlaylistsIDs() (ids []int) {
	for id := range m.removedplaylists {
		ids = append(ids, id)
	}
	return
}

// PlaylistsIDs returns the playlists ids in the mutation.
func (m *UserMutation) PlaylistsIDs() (ids []int) {
	for id := range m.playlists {
		ids = append(ids, id)
	}
	return
}

// ResetPlaylists reset all changes of the "playlists" edge.
func (m *UserMutation) ResetPlaylists() {
	m.playlists = nil
	m.removedplaylists = nil
}

// AddVideoIDs adds the videos edge to Video by ids.
func (m *UserMutation) AddVideoIDs(ids ...int) {
	if m.videos == nil {
		m.videos = make(map[int]struct{})
	}
	for i := range ids {
		m.videos[ids[i]] = struct{}{}
	}
}

// RemoveVideoIDs removes the videos edge to Video by ids.
func (m *UserMutation) RemoveVideoIDs(ids ...int) {
	if m.removedvideos == nil {
		m.removedvideos = make(map[int]struct{})
	}
	for i := range ids {
		m.removedvideos[ids[i]] = struct{}{}
	}
}

// RemovedVideos returns the removed ids of videos.
func (m *UserMutation) RemovedVideosIDs() (ids []int) {
	for id := range m.removedvideos {
		ids = append(ids, id)
	}
	return
}

// VideosIDs returns the videos ids in the mutation.
func (m *UserMutation) VideosIDs() (ids []int) {
	for id := range m.videos {
		ids = append(ids, id)
	}
	return
}

// ResetVideos reset all changes of the "videos" edge.
func (m *UserMutation) ResetVideos() {
	m.videos = nil
	m.removedvideos = nil
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.age != nil {
		fields = append(fields, user.FieldAge)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldEmail:
		return m.Email()
	case user.FieldPassword:
		return m.Password()
	case user.FieldAge:
		return m.Age()
	case user.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldAge:
		return m.OldAge(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAge(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *UserMutation) AddedFields() []string {
	var fields []string
	if m.addage != nil {
		fields = append(fields, user.FieldAge)
	}
	return fields
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case user.FieldAge:
		return m.AddedAge()
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case user.FieldAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAge(v)
		return nil
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldAge:
		m.ResetAge()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.playlists != nil {
		edges = append(edges, user.EdgePlaylists)
	}
	if m.videos != nil {
		edges = append(edges, user.EdgeVideos)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgePlaylists:
		ids := make([]ent.Value, 0, len(m.playlists))
		for id := range m.playlists {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeVideos:
		ids := make([]ent.Value, 0, len(m.videos))
		for id := range m.videos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedplaylists != nil {
		edges = append(edges, user.EdgePlaylists)
	}
	if m.removedvideos != nil {
		edges = append(edges, user.EdgeVideos)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgePlaylists:
		ids := make([]ent.Value, 0, len(m.removedplaylists))
		for id := range m.removedplaylists {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeVideos:
		ids := make([]ent.Value, 0, len(m.removedvideos))
		for id := range m.removedvideos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgePlaylists:
		m.ResetPlaylists()
		return nil
	case user.EdgeVideos:
		m.ResetVideos()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// VideoMutation represents an operation that mutate the Videos
// nodes in the graph.
type VideoMutation struct {
	config
	op                     Op
	typ                    string
	id                     *int
	video_title            *string
	clearedFields          map[string]struct{}
	playlist_videos        map[int]struct{}
	removedplaylist_videos map[int]struct{}
	owner                  *int
	clearedowner           bool
	done                   bool
	oldValue               func(context.Context) (*Video, error)
}

var _ ent.Mutation = (*VideoMutation)(nil)

// videoOption allows to manage the mutation configuration using functional options.
type videoOption func(*VideoMutation)

// newVideoMutation creates new mutation for $n.Name.
func newVideoMutation(c config, op Op, opts ...videoOption) *VideoMutation {
	m := &VideoMutation{
		config:        c,
		op:            op,
		typ:           TypeVideo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVideoID sets the id field of the mutation.
func withVideoID(id int) videoOption {
	return func(m *VideoMutation) {
		var (
			err   error
			once  sync.Once
			value *Video
		)
		m.oldValue = func(ctx context.Context) (*Video, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Video.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVideo sets the old Video of the mutation.
func withVideo(node *Video) videoOption {
	return func(m *VideoMutation) {
		m.oldValue = func(context.Context) (*Video, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VideoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VideoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *VideoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetVideoTitle sets the video_title field.
func (m *VideoMutation) SetVideoTitle(s string) {
	m.video_title = &s
}

// VideoTitle returns the video_title value in the mutation.
func (m *VideoMutation) VideoTitle() (r string, exists bool) {
	v := m.video_title
	if v == nil {
		return
	}
	return *v, true
}

// OldVideoTitle returns the old video_title value of the Video.
// If the Video object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *VideoMutation) OldVideoTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldVideoTitle is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldVideoTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVideoTitle: %w", err)
	}
	return oldValue.VideoTitle, nil
}

// ResetVideoTitle reset all changes of the "video_title" field.
func (m *VideoMutation) ResetVideoTitle() {
	m.video_title = nil
}

// AddPlaylistVideoIDs adds the playlist_videos edge to PlaylistVideo by ids.
func (m *VideoMutation) AddPlaylistVideoIDs(ids ...int) {
	if m.playlist_videos == nil {
		m.playlist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.playlist_videos[ids[i]] = struct{}{}
	}
}

// RemovePlaylistVideoIDs removes the playlist_videos edge to PlaylistVideo by ids.
func (m *VideoMutation) RemovePlaylistVideoIDs(ids ...int) {
	if m.removedplaylist_videos == nil {
		m.removedplaylist_videos = make(map[int]struct{})
	}
	for i := range ids {
		m.removedplaylist_videos[ids[i]] = struct{}{}
	}
}

// RemovedPlaylistVideos returns the removed ids of playlist_videos.
func (m *VideoMutation) RemovedPlaylistVideosIDs() (ids []int) {
	for id := range m.removedplaylist_videos {
		ids = append(ids, id)
	}
	return
}

// PlaylistVideosIDs returns the playlist_videos ids in the mutation.
func (m *VideoMutation) PlaylistVideosIDs() (ids []int) {
	for id := range m.playlist_videos {
		ids = append(ids, id)
	}
	return
}

// ResetPlaylistVideos reset all changes of the "playlist_videos" edge.
func (m *VideoMutation) ResetPlaylistVideos() {
	m.playlist_videos = nil
	m.removedplaylist_videos = nil
}

// SetOwnerID sets the owner edge to User by id.
func (m *VideoMutation) SetOwnerID(id int) {
	m.owner = &id
}

// ClearOwner clears the owner edge to User.
func (m *VideoMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared returns if the edge owner was cleared.
func (m *VideoMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the owner id in the mutation.
func (m *VideoMutation) OwnerID() (id int, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the owner ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *VideoMutation) OwnerIDs() (ids []int) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner reset all changes of the "owner" edge.
func (m *VideoMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// Op returns the operation name.
func (m *VideoMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Video).
func (m *VideoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *VideoMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.video_title != nil {
		fields = append(fields, video.FieldVideoTitle)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *VideoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case video.FieldVideoTitle:
		return m.VideoTitle()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *VideoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case video.FieldVideoTitle:
		return m.OldVideoTitle(ctx)
	}
	return nil, fmt.Errorf("unknown Video field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *VideoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case video.FieldVideoTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVideoTitle(v)
		return nil
	}
	return fmt.Errorf("unknown Video field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *VideoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *VideoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *VideoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Video numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *VideoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *VideoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *VideoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Video nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *VideoMutation) ResetField(name string) error {
	switch name {
	case video.FieldVideoTitle:
		m.ResetVideoTitle()
		return nil
	}
	return fmt.Errorf("unknown Video field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *VideoMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.playlist_videos != nil {
		edges = append(edges, video.EdgePlaylistVideos)
	}
	if m.owner != nil {
		edges = append(edges, video.EdgeOwner)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *VideoMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case video.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.playlist_videos))
		for id := range m.playlist_videos {
			ids = append(ids, id)
		}
		return ids
	case video.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *VideoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedplaylist_videos != nil {
		edges = append(edges, video.EdgePlaylistVideos)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *VideoMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case video.EdgePlaylistVideos:
		ids := make([]ent.Value, 0, len(m.removedplaylist_videos))
		for id := range m.removedplaylist_videos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *VideoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, video.EdgeOwner)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *VideoMutation) EdgeCleared(name string) bool {
	switch name {
	case video.EdgeOwner:
		return m.clearedowner
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *VideoMutation) ClearEdge(name string) error {
	switch name {
	case video.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Video unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *VideoMutation) ResetEdge(name string) error {
	switch name {
	case video.EdgePlaylistVideos:
		m.ResetPlaylistVideos()
		return nil
	case video.EdgeOwner:
		m.ResetOwner()
		return nil
	}
	return fmt.Errorf("unknown Video edge %s", name)
}
