// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/pongsakorn-maker/entgo-playground/ent/playlistvideo"
	"github.com/pongsakorn-maker/entgo-playground/ent/predicate"
	"github.com/pongsakorn-maker/entgo-playground/ent/user"
	"github.com/pongsakorn-maker/entgo-playground/ent/video"
)

// VideoUpdate is the builder for updating Video entities.
type VideoUpdate struct {
	config
	hooks      []Hook
	mutation   *VideoMutation
	predicates []predicate.Video
}

// Where adds a new predicate for the builder.
func (vu *VideoUpdate) Where(ps ...predicate.Video) *VideoUpdate {
	vu.predicates = append(vu.predicates, ps...)
	return vu
}

// SetVideoID sets the video_id field.
func (vu *VideoUpdate) SetVideoID(i int) *VideoUpdate {
	vu.mutation.ResetVideoID()
	vu.mutation.SetVideoID(i)
	return vu
}

// AddVideoID adds i to video_id.
func (vu *VideoUpdate) AddVideoID(i int) *VideoUpdate {
	vu.mutation.AddVideoID(i)
	return vu
}

// AddPlaylistVideoIDs adds the playlist_videos edge to PlaylistVideo by ids.
func (vu *VideoUpdate) AddPlaylistVideoIDs(ids ...int) *VideoUpdate {
	vu.mutation.AddPlaylistVideoIDs(ids...)
	return vu
}

// AddPlaylistVideos adds the playlist_videos edges to PlaylistVideo.
func (vu *VideoUpdate) AddPlaylistVideos(p ...*PlaylistVideo) *VideoUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vu.AddPlaylistVideoIDs(ids...)
}

// SetOwnerID sets the owner edge to User by id.
func (vu *VideoUpdate) SetOwnerID(id int) *VideoUpdate {
	vu.mutation.SetOwnerID(id)
	return vu
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (vu *VideoUpdate) SetNillableOwnerID(id *int) *VideoUpdate {
	if id != nil {
		vu = vu.SetOwnerID(*id)
	}
	return vu
}

// SetOwner sets the owner edge to User.
func (vu *VideoUpdate) SetOwner(u *User) *VideoUpdate {
	return vu.SetOwnerID(u.ID)
}

// Mutation returns the VideoMutation object of the builder.
func (vu *VideoUpdate) Mutation() *VideoMutation {
	return vu.mutation
}

// RemovePlaylistVideoIDs removes the playlist_videos edge to PlaylistVideo by ids.
func (vu *VideoUpdate) RemovePlaylistVideoIDs(ids ...int) *VideoUpdate {
	vu.mutation.RemovePlaylistVideoIDs(ids...)
	return vu
}

// RemovePlaylistVideos removes playlist_videos edges to PlaylistVideo.
func (vu *VideoUpdate) RemovePlaylistVideos(p ...*PlaylistVideo) *VideoUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vu.RemovePlaylistVideoIDs(ids...)
}

// ClearOwner clears the owner edge to User.
func (vu *VideoUpdate) ClearOwner() *VideoUpdate {
	vu.mutation.ClearOwner()
	return vu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (vu *VideoUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(vu.hooks) == 0 {
		affected, err = vu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VideoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vu.mutation = mutation
			affected, err = vu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vu.hooks) - 1; i >= 0; i-- {
			mut = vu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VideoUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VideoUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VideoUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vu *VideoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   video.Table,
			Columns: video.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: video.FieldID,
			},
		},
	}
	if ps := vu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.VideoID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: video.FieldVideoID,
		})
	}
	if value, ok := vu.mutation.AddedVideoID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: video.FieldVideoID,
		})
	}
	if nodes := vu.mutation.RemovedPlaylistVideosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   video.PlaylistVideosTable,
			Columns: []string{video.PlaylistVideosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: playlistvideo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.PlaylistVideosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   video.PlaylistVideosTable,
			Columns: []string{video.PlaylistVideosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: playlistvideo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   video.OwnerTable,
			Columns: []string{video.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   video.OwnerTable,
			Columns: []string{video.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{video.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// VideoUpdateOne is the builder for updating a single Video entity.
type VideoUpdateOne struct {
	config
	hooks    []Hook
	mutation *VideoMutation
}

// SetVideoID sets the video_id field.
func (vuo *VideoUpdateOne) SetVideoID(i int) *VideoUpdateOne {
	vuo.mutation.ResetVideoID()
	vuo.mutation.SetVideoID(i)
	return vuo
}

// AddVideoID adds i to video_id.
func (vuo *VideoUpdateOne) AddVideoID(i int) *VideoUpdateOne {
	vuo.mutation.AddVideoID(i)
	return vuo
}

// AddPlaylistVideoIDs adds the playlist_videos edge to PlaylistVideo by ids.
func (vuo *VideoUpdateOne) AddPlaylistVideoIDs(ids ...int) *VideoUpdateOne {
	vuo.mutation.AddPlaylistVideoIDs(ids...)
	return vuo
}

// AddPlaylistVideos adds the playlist_videos edges to PlaylistVideo.
func (vuo *VideoUpdateOne) AddPlaylistVideos(p ...*PlaylistVideo) *VideoUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vuo.AddPlaylistVideoIDs(ids...)
}

// SetOwnerID sets the owner edge to User by id.
func (vuo *VideoUpdateOne) SetOwnerID(id int) *VideoUpdateOne {
	vuo.mutation.SetOwnerID(id)
	return vuo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (vuo *VideoUpdateOne) SetNillableOwnerID(id *int) *VideoUpdateOne {
	if id != nil {
		vuo = vuo.SetOwnerID(*id)
	}
	return vuo
}

// SetOwner sets the owner edge to User.
func (vuo *VideoUpdateOne) SetOwner(u *User) *VideoUpdateOne {
	return vuo.SetOwnerID(u.ID)
}

// Mutation returns the VideoMutation object of the builder.
func (vuo *VideoUpdateOne) Mutation() *VideoMutation {
	return vuo.mutation
}

// RemovePlaylistVideoIDs removes the playlist_videos edge to PlaylistVideo by ids.
func (vuo *VideoUpdateOne) RemovePlaylistVideoIDs(ids ...int) *VideoUpdateOne {
	vuo.mutation.RemovePlaylistVideoIDs(ids...)
	return vuo
}

// RemovePlaylistVideos removes playlist_videos edges to PlaylistVideo.
func (vuo *VideoUpdateOne) RemovePlaylistVideos(p ...*PlaylistVideo) *VideoUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return vuo.RemovePlaylistVideoIDs(ids...)
}

// ClearOwner clears the owner edge to User.
func (vuo *VideoUpdateOne) ClearOwner() *VideoUpdateOne {
	vuo.mutation.ClearOwner()
	return vuo
}

// Save executes the query and returns the updated entity.
func (vuo *VideoUpdateOne) Save(ctx context.Context) (*Video, error) {

	var (
		err  error
		node *Video
	)
	if len(vuo.hooks) == 0 {
		node, err = vuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VideoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vuo.mutation = mutation
			node, err = vuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vuo.hooks) - 1; i >= 0; i-- {
			mut = vuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VideoUpdateOne) SaveX(ctx context.Context) *Video {
	v, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query on the entity.
func (vuo *VideoUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VideoUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vuo *VideoUpdateOne) sqlSave(ctx context.Context) (v *Video, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   video.Table,
			Columns: video.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: video.FieldID,
			},
		},
	}
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Video.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := vuo.mutation.VideoID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: video.FieldVideoID,
		})
	}
	if value, ok := vuo.mutation.AddedVideoID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: video.FieldVideoID,
		})
	}
	if nodes := vuo.mutation.RemovedPlaylistVideosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   video.PlaylistVideosTable,
			Columns: []string{video.PlaylistVideosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: playlistvideo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.PlaylistVideosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   video.PlaylistVideosTable,
			Columns: []string{video.PlaylistVideosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: playlistvideo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if vuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   video.OwnerTable,
			Columns: []string{video.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   video.OwnerTable,
			Columns: []string{video.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	v = &Video{config: vuo.config}
	_spec.Assign = v.assignValues
	_spec.ScanValues = v.scanValues()
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{video.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return v, nil
}
